### ISSUE TITLE
Import to IOBROKER

### ISSUE THREAD

**Issue by rieders** [dr-ni/mi600#1]
Hi
Thank you for the script to get the inverter values.
It works perfectly.
How can I insert and bundle the information in iobroker.
I have seen that many types provide the same information.
Very nice work without having to access a cloud.

I would be happy if there is a possibility to import the data into Iobroker.

Greetings Andre

**Comment by dr-ni** [comment]
Hi Andre,

I'm not familar with iobroker, however it might be possible like shown in this example?
https://www.smarthome-tricks.de/software-iobroker/iobroker-javascript-exec/

Cheers Uwe

**Comment by dr-ni** [comment]
or something similar
https://iobroker.blogspot.com/2017/07/sonne-in-den-tank.html

**Comment by rieders** [comment]
Hallo

Vielen Dank für die Informationen.

Ich muss mich in den Nächsten Tagen mal damit beschäftigen.

Leider hab ich mich bisher noch nicht so recht an das Thema Script herangetraut.

 

Grüße André

 

Von: dr-ni ***@***.***> 
Gesendet: Freitag, 22. April 2022 14:26
An: dr-ni/mi600 ***@***.***>
Cc: A. Rieth ***@***.***>; Author ***@***.***>
Betreff: Re: [dr-ni/mi600] Import to IOBROKER (Issue #1)

 

or something similar
https://iobroker.blogspot.com/2017/07/sonne-in-den-tank.html

**Comment by dr-ni** [comment]
https://www.smarthome-tricks.de/software-iobroker/eigene-datenpunkte-in-iobroker-anlegen/
https://digitaldad.de/2022/03/27/iobroker-visualisierung-statusanzeige-energie-solardaten/
