### ISSUE TITLE
More comments and explanations

### ISSUE THREAD

**Issue by RaptorSDS** [dr-ni/mi600#4]
Please can you give a little more comments and explanations about the steps ( loops) 

not all are so deep in bash and would like to improve bash skills as well.

I'm trying to include this script in a project " Volkzähler " visiualization of energy consumption for my home.

to do this it is enough for me to query the data every few minutes as in your script and send the values to the database via json request.

Translated with www.DeepL.com/Translator (free version)

**Comment by dr-ni** [comment]
loops:
https://stackoverflow.com/questions/17394356/how-can-i-make-a-bash-command-run-periodically

a very simple bash script example for json format:
```
#!/bin/bash
host="mi600-hostname-or-IP"
user="username"
password="yourpw"

#TOTAL=$(/usr/local/bin/mi600 $host $user $password webdata_total_e)
DAY=$(/usr/local/bin/mi600 $host $user $password webdata_today_e)
#ACTUAL=$(/usr/local/bin/mi600 $host $user $password)

echo '{"Today":"'$DAY'"}'
```

**Comment by RaptorSDS** [comment]
thank you also for this information about bash
