### ISSUE TITLE
value without Unit

### ISSUE THREAD

**Issue by RaptorSDS** [dr-ni/mi600#5]
Is it possible that you add some extract string  with the value but without extension Unit "W" or "kWh"

or a switch that that extract the 4 value and jump over your then
  dat=$4
  val=''
  [ "$dat" = "webdata_today_e" ] && val=kWh
  [ "$dat" = "webdata_total_e" ] && val=kWh
  [ "$dat" = "webdata_now_p" ] && val=W
fi

**Comment by dr-ni** [comment]
Please can you test the new v1.0.2
Itshould be switchable now with -u

**Comment by RaptorSDS** [comment]
thank you 
works now with my script , all data now recived by volkzähler DB

**Comment by RaptorSDS** [comment]
Thanks again 

I hope it is ok for you that I mention you at Volkszähler DB project and refer to your Github project there. 

https://wiki.volkszaehler.org/hardware/channels/solar_inverters/deye

**Comment by dr-ni** [comment]
yes of course :-)

**Comment by dr-ni** [comment]
As I can see you are using standart settings admin admin. This is insecure!!
Never use standart settings.

Attack:
https://github.com/s10l/deye-logger-at-cmd.git

Firmware update:
https://zinnzgreen.de/service/deye-mikrowechselrichter-systemupdate/
then reset and change the AP password (max 8 chars)

**Comment by RaptorSDS** [comment]
thank you for your information , update already installed  
AP pass already change

**Comment by dr-ni** [comment]
*/5 * * * * /bin/bash /home/pi/devo.sh

ahould be

*/5 * * * * /bin/bash /home/pi/auslesen.sh

**Comment by dr-ni** [comment]
also the install cmd should be "sudo make install" instead of "make install"
